HairContainer/Hair/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hair.Models;

namespace Hair.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly HairContext _context;

        public AppointmentController(HairContext context)
        {
            _context = context;
        }

        // GET: Appointment
        public async Task<IActionResult> Index()
        {
            var hairContext = _context.Appointment.Include(a => a.Customer).Include(a => a.Staff);
            return View(await hairContext.ToListAsync());
        }

        // GET: Appointment/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment
                .Include(a => a.Customer)
                .Include(a => a.Staff)
                .FirstOrDefaultAsync(m => m.AppointmentId == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // GET: Appointment/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "Name");
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId");
            return View();
        }

        // POST: Appointment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AppointmentId,CustomerId,StaffId,AppointmentDate,ScheduledStartTime,ProcedureMinutes,ScheduledEndTime,FinalTotal,TotalBeforeTax,TaxRate,Completed")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appointment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "Name", appointment.CustomerId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId", appointment.StaffId);
            return View(appointment);
        }

        // GET: Appointment/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "Name", appointment.CustomerId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId", appointment.StaffId);
            return View(appointment);
        }

        // POST: Appointment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AppointmentId,CustomerId,StaffId,AppointmentDate,ScheduledStartTime,ProcedureMinutes,ScheduledEndTime,FinalTotal,TotalBeforeTax,TaxRate,Completed")] Appointment appointment)
        {
            if (id != appointment.AppointmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.AppointmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "Name", appointment.CustomerId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "StaffId", "StaffId", appointment.StaffId);
            return View(appointment);
        }

        // GET: Appointment/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment
                .Include(a => a.Customer)
                .Include(a => a.Staff)
                .FirstOrDefaultAsync(m => m.AppointmentId == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appointment = await _context.Appointment.FindAsync(id);
            _context.Appointment.Remove(appointment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(int id)
        {
            return _context.Appointment.Any(e => e.AppointmentId == id);
        }
    }
}

HairContainer/Hair/Controllers/AppointmentDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hair.Models;
using Microsoft.AspNetCore.Http;

namespace Hair.Controllers
{
    public class AppointmentDetailController : Controller
    {
        private readonly HairContext _context;

        public AppointmentDetailController(HairContext context)
        {
            _context = context;
        }

        // GET: AppointmentDetail
        public async Task<IActionResult> Index(string AppointmentId)
        {
            if (AppointmentId!=null)
            {
                HttpContext.Session.SetString(nameof(AppointmentId), AppointmentId.ToString());
            }
            else if (HttpContext.Session.GetString("AppointmentId")!=null)
            {
                AppointmentId = HttpContext.Session.GetString("AppointmentId");
            }
            else
            {
                TempData["message"] = "Please select appointement first to show the details";
                return RedirectToAction("Index", "Appointment");
            }

            var totalMinutes = _context.AppointmentDetail.Sum(a => a.ProcedureMinutes);
            ViewData["totalMinutes"] = totalMinutes.ToString();

            var hairContext = _context.AppointmentDetail.Include(a => a.Appointment)
                .Include(a => a.Product).Where(a=>a.AppointmentId==int.Parse(AppointmentId));
            return View(await hairContext.ToListAsync());
        }

        // GET: AppointmentDetail/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointmentDetail = await _context.AppointmentDetail
                .Include(a => a.Appointment)
                .Include(a => a.Product)
                .FirstOrDefaultAsync(m => m.AppointmentDetailId == id);
            if (appointmentDetail == null)
            {
                return NotFound();
            }

            return View(appointmentDetail);
        }

        // GET: AppointmentDetail/Create
        public IActionResult Create()
        {
            ViewData["AppointmentId"] = new SelectList(_context.Appointment, "AppointmentId", "AppointmentId");
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "Name");
            return View();
        }

        // POST: AppointmentDetail/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AppointmentDetailId,AppointmentId,ProductId,ProcedureMinutes,RetailPrice,Quantity,Discount,Total,Comments")] AppointmentDetail appointmentDetail)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(appointmentDetail);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Appointment Created";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {

                TempData["message"] = "Create Failed" + ex.GetBaseException().Message;
            }
            ViewData["AppointmentId"] = new SelectList(_context.Appointment, "AppointmentId", "AppointmentId", appointmentDetail.AppointmentId);
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "Name", appointmentDetail.ProductId);
            return View(appointmentDetail);
        }

        // GET: AppointmentDetail/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointmentDetail = await _context.AppointmentDetail.FindAsync(id);
            if (appointmentDetail == null)
            {
                return NotFound();
            }
            ViewData["AppointmentId"] = new SelectList(_context.Appointment, "AppointmentId", "AppointmentId", appointmentDetail.AppointmentId);
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "Name", appointmentDetail.ProductId);
            return View(appointmentDetail);
        }

        // POST: AppointmentDetail/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AppointmentDetailId,AppointmentId,ProductId,ProcedureMinutes,RetailPrice,Quantity,Discount,Total,Comments")] AppointmentDetail appointmentDetail)
        {
            if (id != appointmentDetail.AppointmentDetailId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointmentDetail);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Record Edited" ;
                }
                //catch (DbUpdateConcurrencyException)
                //{
                catch(Exception ex)
                { 
                    if (!AppointmentDetailExists(appointmentDetail.AppointmentDetailId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        TempData["message"] = "Edit Failed" + ex.GetBaseException().Message;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppointmentId"] = new SelectList(_context.Appointment, "AppointmentId", "AppointmentId", appointmentDetail.AppointmentId);
            ViewData["ProductId"] = new SelectList(_context.Product, "ProductId", "Name", appointmentDetail.ProductId);
            return View(appointmentDetail);
        }

        // GET: AppointmentDetail/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointmentDetail = await _context.AppointmentDetail
                .Include(a => a.Appointment)
                .Include(a => a.Product)
                .FirstOrDefaultAsync(m => m.AppointmentDetailId == id);
            if (appointmentDetail == null)
            {
                return NotFound();
            }

            return View(appointmentDetail);
        }

        // POST: AppointmentDetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var appointmentDetail = await _context.AppointmentDetail.FindAsync(id);
                _context.AppointmentDetail.Remove(appointmentDetail);
                await _context.SaveChangesAsync();
                TempData["message"] = "Deleted";
                
               
            }
            catch (Exception ex)
            {

                TempData["message"] = "Delete Failed" + ex.GetBaseException().Message;
            }
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentDetailExists(int id)
        {
            return _context.AppointmentDetail.Any(e => e.AppointmentDetailId == id);
        }
    }
}

HairContainer/Hair/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hair</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Hair</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Appointment" asp-action="Index">Appointment</a></li>
                    <li><a asp-area="" asp-controller="AppointmentDetail" asp-action="Index">AppointmentDetail</a></li>

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    <div style="color:red; font-weight:bold; text-align:center;"><span>@TempData["message"]</span></div>
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div>
                <div style="float:left;">
                    <br />
                    <a href="mailto:aelgendy7114@conestogac.on.ca">Azza Elgendy section 2</a>
                </div>
                <div style="float:right;">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>